Fix makefile/script warnings and apollo script compilation issues & cpuidle-ucc dtb (#7)
* apollo.sh: add older script to avoid weird script errors

* temporarily

* arch/arm64/configs/exynos9810_defconfig: remove duplicated configs & the ones that existed in ds_defconfig

* drivers/samsung: fix Kconfig warns

drivers/samsung/debug/Kconfig:51:warning: ignoring type redefinition of 'SEC_DEBUG_TSP_LOG' from 'tristate' to 'boolean'
drivers/samsung/misc/Kconfig:7:warning: ignoring type redefinition of 'SEC_DEBUG_TSP_LOG' from 'tristate' to 'boolean'

* drivers/samsung/misc/Kconfig: fix warn

* drivers/samsung/misc/Kconfig:87:warning: leading whitespace ignored

* kconfig: Kconfig:11:warning: environment variable ANDROID_VERSION undefined

* not used

* Revert "makefile: ignore more warnings"

This reverts commit 8a673489cf5671e83c236090988cf278567d908c.

* Revert "makefile: disable some GCC8 warnings"

This reverts commit 5a3dbe7dc9431fa3f57ff39f6f904097b1270c58.

* kernel/printk/printk: fix warning

* kernel/printk/printk.c:761:5: warning: 'CONFIG_SEC_DEBUG_FIRST_KMSG' is not defined, evaluates to 0 [-Wundef]
* kernel/printk/printk.c:618:5: warning: 'CONFIG_SEC_DEBUG_FIRST_KMSG' is not defined, evaluates to 0 [-Wundef]
  618 | #if CONFIG_SEC_DEBUG_FIRST_KMSG
      |     ^

* include/linux/battery: fix warning

* ./include/linux/battery/battery_notifier.h:27:9: warning: 'AVAILABLE_VOLTAGE' macro redefined [-Wmacro-redefined]
   27 | #define AVAILABLE_VOLTAGE 9000
      |         ^
./include/linux/ccic/s2mm005.h:44:9: note: previous definition is here
   44 | #define AVAILABLE_VOLTAGE 12000

* drivers/input/touchscreen/sec_ts: fix warnings

* drivers/input/touchscreen/sec_ts/sec_ts_fn.c:1127:22: note: change the argument to be the free space in the destination buffer minus the terminating null byte
 1127 |         strncat(buff, temp, sizeof(temp));
      |                             ^~~~~~~~~~~~
      |                             sizeof(buff) - strlen(buff) - 1

* sec_debug: silence null-dereference warnings

Signed-off-by: Michael Benedict <michaelbt@live.com>
Change-Id: I435ca27cecc73e4754fe7da47f47beb4d3b4784a

* sensorhub: bbdpl: Drop redefinition of types

Change-Id: I7f3a1f6613dcd23b8bf1ddc18d69c718d0335be8

* kconfig: display recursive dependency resolution hint just once

commit e3b03bf29d6b99fab7001fb20c33fe54928c157a upstream.

Commit 1c199f2878f6 ("kbuild: document recursive dependency limitation
/ resolution") probably intended to show a hint along with "recursive
dependency detected!" error, but it missed to add {...} guard, and the
hint is displayed in every loop of the dep_stack traverse, annoyingly.

This error was detected by GCC's -Wmisleading-indentation when switching
to build-time generation of lexer/parser.

scripts/kconfig/symbol.c: In function ‘sym_check_print_recursive’:
scripts/kconfig/symbol.c:1150:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
   if (stack->sym == last_sym)
   ^~
scripts/kconfig/symbol.c:1153:4: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
    fprintf(stderr, "For a resolution refer to Documentation/kbuild/kconfig-language.txt\n");
    ^~~~~~~

I could simply add {...} to surround the three fprintf(), but I rather
chose to move the hint after the loop to make the whole message readable.

Fixes: 1c199f2878f6 ("kbuild: document recursive dependency limitation / resolution"
Signed-off-by: Masahiro Yamada <yamada.masahiro@socionext.com>
Acked-by: Luis R. Rodriguez <mcgrof@kernel.org>
Cc: Daniel Díaz <daniel.diaz@linaro.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

* drivers/input/wacom: port from N9 OSRC

* drivers/input/wacom: sec_class conversion

* makefile: fix /bin/sh: 1: Syntax error: "(" unexpected

* trace: exynos-ss: Drop redefinition of ess_initcall_t

Change-Id: If4305707ac3acbe0b47129e6e33d5e89da6025bf

* drivers/sensorhub/brcm/factory: fix compiler warning

drivers/sensorhub/brcm/factory/light_colorid.c:558:30: warning: 'sscanf' may overflow; destination buffer in argument 3 has size 20, but the corresponding specifier may require size 21 [-Wfortify-source]
  558 |                 iRet = sscanf(str, %20s, str_ids);

* drivers/staging/android/ion/exynos: fix compiler warning

* drivers/staging/android/ion/exynos/exynos_ion.c:279:26: warning: unused variable 'info' [-Wunused-variable]
  279 |         struct ion_buffer_info *info = (struct ion_buffer_info *)buffer->priv_virt;

* Revert "kconfig: Kconfig:11:warning: environment variable ANDROID_VERSION undefined"

This reverts commit f744d5c5a381ac8a5d60c733a567455eff33dc2d.

* drivers: gpu: arm: kconfig: fix 'redefining environment symbol from ANDROID_VERSION'

* kconfig: Kconfig:11:warning: environment variable ANDROID_VERSION undefined

* not used

* DS/Ramdisk: add placeholders

* DS/Product: add placeholder

* apollo: export ANDROID_VERSION

* misc updates

* dts: exynos9810: add cpuidle-ucc

---------

Signed-off-by: Michael Benedict <michaelbt@live.com>
Signed-off-by: Masahiro Yamada <yamada.masahiro@socionext.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Co-authored-by: Michael Benedict <michaelbt@live.com>
Co-authored-by: FAROVITUS <farovitus@gmail.com>
Co-authored-by: Masahiro Yamada <yamada.masahiro@socionext.com>
Co-authored-by: Erfan Abdi <erfangplus@gmail.com>
Co-authored-by: Anan Jaser <ananjaser@gmail.com>